[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--version"
  NPM_CONFIG_USERCONFIG = "/dev/null"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PNPM_VERSION = "8"
  NETLIFY_USE_PNPM = "true"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/next"
